add_subdirectory(01_hardcode_triangle)
add_subdirectory(02_vertex_buffer_triangle)
add_subdirectory(03_indexed_rectangle)
add_subdirectory(04_planar_triangle)
add_subdirectory(04.5_sub-allocation_triangle)
add_subdirectory(05_uniform)
add_subdirectory(05.5_bindLayoutEntry)
add_subdirectory(06_depth_culling_msaa)
add_subdirectory(07_texture_samplers)
add_subdirectory(08_mipmaps)
add_subdirectory(09_instanced_rendering)
add_subdirectory(10_buffer_mapping)
add_subdirectory(11_compute)
add_subdirectory(11.5_fractal_mandelbort)
add_subdirectory(12_rendering_compute)
add_subdirectory(13_offscreen_rendering)
add_subdirectory(14_workgroup_barriers)