add_subdirectory(01_hardcode_triangle)
add_subdirectory(02_vertex_buffer_triangle)
add_subdirectory(03_indexed_rectangle)
add_subdirectory(04_planar_triangle)
add_subdirectory(04.5_sub-allocation_triangle)
add_subdirectory(05_uniform)
add_subdirectory(05.5_bindLayoutEntry)
add_subdirectory(06_depth_culling_msaa)
add_subdirectory(07_texture_samplers)
add_subdirectory(08_mipmaps)
add_subdirectory(09_instanced_rendering)
