add_subdirectory(01_00_hardcode_triangle)
add_subdirectory(02_00_vertex_buffer_triangle)
add_subdirectory(03_00_indexed_rectangle)
add_subdirectory(04_00_planar_triangle)
add_subdirectory(04_01_sub-allocation_triangle)
add_subdirectory(05_00_uniform)
add_subdirectory(05_01_bindLayoutEntry)
add_subdirectory(06_00_depth_culling_msaa)
add_subdirectory(07_00_texture_samplers)
add_subdirectory(08_00_mipmaps)
add_subdirectory(09_00_instanced_rendering)
add_subdirectory(10_00_buffer_mapping)
add_subdirectory(11_00_compute)
add_subdirectory(11_01_fractal_mandelbort)
add_subdirectory(12_00_rendering_compute)
add_subdirectory(13_00_offscreen_rendering)
add_subdirectory(14_00_workgroup_barriers)
add_subdirectory(15_00_alpha_blending)
add_subdirectory(16_00_compute_storage_texture)